#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * Native gameplay tags for HollowWilds.
 *
 * Declared with UE_DECLARE_GAMEPLAY_TAG_EXTERN here and defined with
 * UE_DEFINE_GAMEPLAY_TAG in HWGameplayTags.cpp. Reference these from any
 * module that needs strongly-typed gameplay tags (abilities, effects, etc).
 */
namespace HWGameplayTags
{
	// Abilities
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_Bolt);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Blink);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Barrier);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Beam);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Nova);

	// Elements
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Fire);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Ice);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Wind);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Earth);

	// Status
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Burn);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Slow);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Freeze);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Lift);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Lava);

	// States
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);

	// Cooldown
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Blink);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Barrier);
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Nova);

	// Data
	HOLLOWWILDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
}
